version: "3.8"

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  relayer_uni6__osmo-test-5:
    image: "ghcr.io/cosmos/relayer:v2.4.1"
    container_name: relayer_osmosis_testnet
    restart: unless-stopped
    entrypoint: /home/relayer/scripts/run_relayer.sh
    environment:
      - MNEMONIC
      - HUB_CHAIN
      - REMOTE_CHAIN=osmo-test-5
    volumes:
      - ./scripts:/home/relayer/scripts
      - ./config:/home/relayer/templates
    expose:
      - 5183
  relayer_uni6__theta-testnet-001:
    image: "ghcr.io/cosmos/relayer:v2.4.1"
    container_name: relayer_cosmoshub_testnet
    restart: unless-stopped
    entrypoint: /home/relayer/scripts/run_relayer.sh
    environment:
      - MNEMONIC
      - HUB_CHAIN
      - REMOTE_CHAIN=theta-testnet-001
    volumes:
      - ./scripts:/home/relayer/scripts
      - ./config:/home/relayer/templates
    expose:
      - 5183
  relayer_uni6__pion-1:
    image: "ghcr.io/cosmos/relayer:v2.4.1"
    container_name: relayer_neutron_testnet
    restart: unless-stopped
    entrypoint: /home/relayer/scripts/run_relayer.sh
    environment:
      - MNEMONIC
      - HUB_CHAIN
      - REMOTE_CHAIN=pion-1
    volumes:
      - ./scripts:/home/relayer/scripts
      - ./config:/home/relayer/templates
    expose:
      - 5183
  relayer_uni6__elgafar-1:
    image: "ghcr.io/cosmos/relayer:v2.4.1"
    container_name: relayer_stargaze_testnet
    restart: unless-stopped
    entrypoint: /home/relayer/scripts/run_relayer.sh
    environment:
      - MNEMONIC
      - HUB_CHAIN
      - REMOTE_CHAIN=elgafar-1
    volumes:
      - ./scripts:/home/relayer/scripts
      - ./config:/home/relayer/templates
    expose:
      - 5183
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
